[env:ch552_raw]
platform = intel_mcs51
board = ch552t
; 强制使用 SDCC 编译器
build_flags = 
    -mmcs51
    --model-small
    -DFREQ_SYS=24000000

upload_protocol = custom
upload_command = wchisp -u flash $SOURCE