[env:ch552_raw]
platform = intel_mcs51
board = ch552t
; 强制使用 SDCC 编译器
build_flags = 
    --model-small
    --xram-size 1024
    --code-size 14336
    -DFREQ_SYS=24000000
    -DCH552
src_filter = +<*> -<usb_vendor.c>

upload_protocol = custom

; 实际在运作的是 wchisp 这个工具
; https://github.com/ch32-rs/wchisp
; 这里的 -u 是指定usb的意思
upload_command = wchisp -u flash $SOURCE