[env:ch552_raw]
platform = intel_mcs51
board = ch552t
; 强制使用 SDCC 编译器
build_flags = 
    -mmcs51
    --model-small

; 烧录工具配置 (使用你之前关注的开源工具)
upload_protocol = custom
upload_command = wchisp flash $SOURCE